name: sync-gitee
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: SHA256:LnUnXFfss2b0j1n39pY6LhpwIcWB/3c8coRYT4xKw8o
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:s-dehua/s-dehua.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:shuai-dehua/shuai-dehua.gitee.io.git
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: shuai-dehua
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: 3d730ff387b54e538c83c3f35f7fbdc3
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: shuai-dehua/shuai-dehua.gitee.io
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master